name = "otpviego-api"
main = "src/worker.js"
compatibility_date = "2025-05-01"

# === D1 (SQLite database) ===
[[d1_databases]]
binding = "DB"
database_name = "otpviego-comments"
database_id = "c594a4fd-6584-4bbc-a74e-ad99b45d49a5"
